apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - telegraf/

  - mosquitto/
  - secrets/mosquitto.yaml

  - influxdb/
  - secrets/influxdb2-auth.yaml
  - secrets/influxdb2-backup.yaml

  - postgresql/
  - secrets/pgo-s3-creds.yaml
  - secrets/pgo-reader.yaml

  - grafana-v5/
  - secrets/grafana.yaml
  - secrets/influxdb2-grafana-auth.yaml

  - paddock/
  - secrets/paddock-settings.yaml
  - secrets/paddock-socialaccounts.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: telegraf
    newTag: "1.27.3"
  - name: paddock
    newName: quay.io/b4mad/paddock
    newTag: b39957f98eb17ebf9f690c406a9d6dd2a6a3ccd6
  - name: docker.io/eclipse-mosquitto
    newTag: "2.0.16-openssl"
