apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/postgresql

patches:
  - target:
      kind: PostgresCluster
      name: db
    patch: |-
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: 12Gi
